#!/bin/bash

if [[ -z $1 ]]; then
  echo "[-] Please supply a commit message followed by the branch to push to.\
            e.g. 'message to commit' 'main'"
  exit 1
fi

echo "[+] The current folder will be pushed to Github's repository"

git add .
git commit -m "$1"

if [[ "$2" == "" ]]; then
  "[+] Changes will be pushed to main"
  branch='main'
  git push -u origin $branch
fi

echo "[+] Changes will be pushed to $2."
git push -u origin $2
